name = "Glycolysis"
uuid = "1acb6d80-f93a-4117-912f-ae4c0dd090a6"
authors = ["Denis-Titov <titov@berkeley.edu> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
