name = "Glycolysis"
uuid = "1acb6d80-f93a-4117-912f-ae4c0dd090a6"
authors = ["Denis-Titov <titov@berkeley.edu> and contributors"]
version = "0.6.1"

[deps]
LabelledArrays = "2ee39098-c373-598a-b85f-a56591580800"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"

[compat]
julia = "1.6"
LabelledArrays = "1.12"
Measurements = "2.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
